export const UPDATE_INITIAL_FORM_DATA = 'UPDATE_INITIAL_FORM_DATA';
export const UPDATE_INITIAL_FORM_DATA_ERROR = 'UPDATE_INITIAL_FORM_DATA';
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const VALIDATE_FIELD = 'VALIDATE_FIELD';
